--------consulta 1---------------------
SELECT ID_CLIENTE, NOMBRE, APELLIDO, PAIS, CANTIDAD_COMPRA, MONTO
FROM (
SELECT CL.ID_CLIENTE, CL.NOMBRE, CL.APELLIDO, PA.NOMBRE PAIS, COUNT(CL.ID_CLIENTE) CANTIDAD_COMPRA, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
FROM CLIENTE CL, ORDEN ORD, PAIS PA, PRODUCTO PR
WHERE ORD.ID_CLIENTE = CL.ID_CLIENTE
    AND CL.ID_PAIS = PA.ID_PAIS
    AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
GROUP BY CL.ID_CLIENTE, CL.NOMBRE, CL.APELLIDO, PA.NOMBRE
ORDER BY CANTIDAD_COMPRA DESC)
WHERE  ROWNUM <=1;

-------------------CONSULTA2----------------------------
SELECT *
FROM (
SELECT *
FROM(
SELECT PR.ID_PRODUCTO, PR.NOMBRE NOMBRE_PRODUCTO, CAT.NOMBRE CATEGORIA_, SUM(ORD.CANTIDAD) CANTIDAD ,SUM(ORD.CANTIDAD * PR.PRECIO) PRECIO_TOTAL
FROM PRODUCTO PR, CATEGORIA CAT, ORDEN ORD
WHERE (ORD.ID_PRODUCTO = PR.ID_PRODUCTO
    AND PR.ID_CATEGORIA = CAT.ID_CATEGORIA) 
GROUP BY PR.ID_PRODUCTO, PR.NOMBRE, CAT.NOMBRE
ORDER BY CANTIDAD ASC
)
WHERE ROWNUM <=5
UNION
SELECT *
FROM(
SELECT PR.ID_PRODUCTO, PR.NOMBRE NOMBRE_PRODUCTO, CAT.NOMBRE CATEGORIA_, SUM(ORD.CANTIDAD) CANTIDAD ,SUM(ORD.CANTIDAD * PR.PRECIO) PRECIO_TOTAL
FROM PRODUCTO PR, CATEGORIA CAT, ORDEN ORD
WHERE (ORD.ID_PRODUCTO = PR.ID_PRODUCTO
    AND PR.ID_CATEGORIA = CAT.ID_CATEGORIA) 
GROUP BY PR.ID_PRODUCTO, PR.NOMBRE, CAT.NOMBRE
ORDER BY CANTIDAD DESC
)
WHERE ROWNUM <=1)
ORDER BY CANTIDAD;

-----------CONSULTA 3--------------------
SELECT ID_VENDOR ID_VENDEDOR, NOMBRE NOMBRE_VENDEDOR, TOTAL_VENDIDO
FROM(
SELECT ORD.ID_VENDOR, VEN.NOMBRE, COUNT(ORD.ID_VENDOR) VENTA,SUM(ORD.CANTIDAD * PR.PRECIO) TOTAL_VENDIDO
FROM VENDEDOR VEN, ORDEN ORD, PRODUCTO PR
WHERE ORD.ID_VENDOR = VEN.ID_VENDEDOR
    AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
GROUP BY ORD.ID_VENDOR, VEN.NOMBRE
ORDER BY TOTAL_VENDIDO DESC
)
WHERE ROWNUM <= 1;

------------- CONSULTA 4----------------
SELECT NOMBRE, MONTO
FROM (
    SELECT PA.NOMBRE, VEN.ID_PAIS, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
    FROM PAIS PA, VENDEDOR VEN, ORDEN ORD, PRODUCTO PR
    WHERE ORD.ID_VENDOR = VEN.ID_VENDEDOR
        AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND VEN.ID_PAIS = PA.ID_PAIS
    GROUP BY VEN.ID_PAIS, PA.NOMBRE
    ORDER BY MONTO DESC
) 
WHERE ROWNUM <= 1
UNION
SELECT NOMBRE, MONTO
FROM (
    SELECT PA.NOMBRE, VEN.ID_PAIS, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
    FROM PAIS PA, VENDEDOR VEN, ORDEN ORD, PRODUCTO PR
    WHERE ORD.ID_VENDOR = VEN.ID_VENDEDOR
        AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND VEN.ID_PAIS = PA.ID_PAIS
    GROUP BY VEN.ID_PAIS, PA.NOMBRE
    ORDER BY MONTO ASC
) 
WHERE ROWNUM <= 1

-------------CONSULTA 5-------------------
SELECT ID_PAIS, NOMBRE, MONTO
FROM (
    SELECT PA.NOMBRE, VEN.ID_PAIS, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
    FROM PAIS PA, CLIENTE VEN, ORDEN ORD, PRODUCTO PR
    WHERE ORD.ID_CLIENTE = VEN.ID_CLIENTE
        AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND VEN.ID_PAIS = PA.ID_PAIS
    GROUP BY VEN.ID_PAIS, PA.NOMBRE
    ORDER BY MONTO DESC
) 
WHERE ROWNUM <= 5
ORDER BY MONTO DESC

--------------CONSULTA 6--------------------
