--------consulta 1---------------------
SELECT ID_CLIENTE, NOMBRE, APELLIDO, PAIS, CANTIDAD_COMPRA, MONTO
FROM (
SELECT CL.ID_CLIENTE, CL.NOMBRE, CL.APELLIDO, PA.NOMBRE PAIS, COUNT(CL.ID_CLIENTE) CANTIDAD_COMPRA, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
FROM CLIENTE CL, ORDEN ORD, PAIS PA, PRODUCTO PR
WHERE ORD.ID_CLIENTE = CL.ID_CLIENTE
    AND CL.ID_PAIS = PA.ID_PAIS
    AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
GROUP BY CL.ID_CLIENTE, CL.NOMBRE, CL.APELLIDO, PA.NOMBRE
ORDER BY CANTIDAD_COMPRA DESC)
WHERE  ROWNUM <=1;

-------------------CONSULTA2----------------------------
SELECT *
FROM (
SELECT *
FROM(
SELECT PR.ID_PRODUCTO, PR.NOMBRE NOMBRE_PRODUCTO, CAT.NOMBRE CATEGORIA_, SUM(ORD.CANTIDAD) CANTIDAD ,SUM(ORD.CANTIDAD * PR.PRECIO) PRECIO_TOTAL
FROM PRODUCTO PR, CATEGORIA CAT, ORDEN ORD
WHERE (ORD.ID_PRODUCTO = PR.ID_PRODUCTO
    AND PR.ID_CATEGORIA = CAT.ID_CATEGORIA) 
GROUP BY PR.ID_PRODUCTO, PR.NOMBRE, CAT.NOMBRE
ORDER BY CANTIDAD ASC
)
WHERE ROWNUM <=5
UNION
SELECT *
FROM(
SELECT PR.ID_PRODUCTO, PR.NOMBRE NOMBRE_PRODUCTO, CAT.NOMBRE CATEGORIA_, SUM(ORD.CANTIDAD) CANTIDAD ,SUM(ORD.CANTIDAD * PR.PRECIO) PRECIO_TOTAL
FROM PRODUCTO PR, CATEGORIA CAT, ORDEN ORD
WHERE (ORD.ID_PRODUCTO = PR.ID_PRODUCTO
    AND PR.ID_CATEGORIA = CAT.ID_CATEGORIA) 
GROUP BY PR.ID_PRODUCTO, PR.NOMBRE, CAT.NOMBRE
ORDER BY CANTIDAD DESC
)
WHERE ROWNUM <=1)
ORDER BY CANTIDAD;

-----------CONSULTA 3--------------------
SELECT ID_VENDOR ID_VENDEDOR, NOMBRE NOMBRE_VENDEDOR, TOTAL_VENDIDO
FROM(
SELECT ORD.ID_VENDOR, VEN.NOMBRE, COUNT(ORD.ID_VENDOR) VENTA,SUM(ORD.CANTIDAD * PR.PRECIO) TOTAL_VENDIDO
FROM VENDEDOR VEN, ORDEN ORD, PRODUCTO PR
WHERE ORD.ID_VENDOR = VEN.ID_VENDEDOR
    AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
GROUP BY ORD.ID_VENDOR, VEN.NOMBRE
ORDER BY TOTAL_VENDIDO DESC
)
WHERE ROWNUM <= 1;

------------- CONSULTA 4----------------
SELECT NOMBRE, MONTO
FROM (
    SELECT PA.NOMBRE, VEN.ID_PAIS, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
    FROM PAIS PA, VENDEDOR VEN, ORDEN ORD, PRODUCTO PR
    WHERE ORD.ID_VENDOR = VEN.ID_VENDEDOR
        AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND VEN.ID_PAIS = PA.ID_PAIS
    GROUP BY VEN.ID_PAIS, PA.NOMBRE
    ORDER BY MONTO DESC
) 
WHERE ROWNUM <= 1
UNION
SELECT NOMBRE, MONTO
FROM (
    SELECT PA.NOMBRE, VEN.ID_PAIS, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
    FROM PAIS PA, VENDEDOR VEN, ORDEN ORD, PRODUCTO PR
    WHERE ORD.ID_VENDOR = VEN.ID_VENDEDOR
        AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND VEN.ID_PAIS = PA.ID_PAIS
    GROUP BY VEN.ID_PAIS, PA.NOMBRE
    ORDER BY MONTO ASC
) 
WHERE ROWNUM <= 1

-------------CONSULTA 5-------------------
SELECT ID_PAIS, NOMBRE, MONTO
FROM (
    SELECT PA.NOMBRE, VEN.ID_PAIS, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
    FROM PAIS PA, CLIENTE VEN, ORDEN ORD, PRODUCTO PR
    WHERE ORD.ID_CLIENTE = VEN.ID_CLIENTE
        AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND VEN.ID_PAIS = PA.ID_PAIS
    GROUP BY VEN.ID_PAIS, PA.NOMBRE
    ORDER BY MONTO DESC
) 
WHERE ROWNUM <= 5
ORDER BY MONTO DESC

--------------CONSULTA 6--------------------
SELECT CATEGORIA_PRODUCTO, CANTIDAD_UNIDADES
FROM(
    SELECT PR.ID_CATEGORIA, CAT.NOMBRE CATEGORIA_PRODUCTO, SUM(ORD.CANTIDAD) CANTIDAD_UNIDADES
    FROM ORDEN ORD, PRODUCTO PR, CATEGORIA CAT
    WHERE ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND PR.ID_CATEGORIA = CAT.ID_CATEGORIA
    GROUP BY  PR.ID_CATEGORIA, CAT.NOMBRE
    ORDER BY CANTIDAD_UNIDADES DESC
)
WHERE ROWNUM<=1
UNION
SELECT CATEGORIA_PRODUCTO, CANTIDAD_UNIDADES
FROM(
    SELECT PR.ID_CATEGORIA, CAT.NOMBRE CATEGORIA_PRODUCTO, SUM(ORD.CANTIDAD) CANTIDAD_UNIDADES
    FROM ORDEN ORD, PRODUCTO PR, CATEGORIA CAT
    WHERE ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND PR.ID_CATEGORIA = CAT.ID_CATEGORIA
    GROUP BY  PR.ID_CATEGORIA, CAT.NOMBRE
    ORDER BY CANTIDAD_UNIDADES ASC
)
WHERE ROWNUM<=1

------------CONSULTA 7------------------------
WITH CAT_TEMP AS(
    SELECT CL.ID_PAIS, PR.ID_CATEGORIA, CAT.NOMBRE CATEGORIA_PRODUCTO, SUM(ORD.CANTIDAD) CANTIDAD_UNIDADES
    FROM ORDEN ORD, PRODUCTO PR, CATEGORIA CAT, CLIENTE CL
    WHERE ORD.ID_PRODUCTO = PR.ID_PRODUCTO
        AND ORD.ID_CLIENTE = CL.ID_CLIENTE
        AND PR.ID_CATEGORIA = CAT.ID_CATEGORIA
    GROUP BY  CL.ID_PAIS,PR.ID_CATEGORIA, CAT.NOMBRE
    ORDER BY CL.ID_PAIS,CANTIDAD_UNIDADES DESC
), PA_TEMP AS(
    SELECT PA.ID_PAIS,PA.NOMBRE, MAX(CAT.CANTIDAD_UNIDADES) CANTIDAD_UNIDAD
    FROM CAT_TEMP CAT, PAIS PA
    WHERE CAT.ID_PAIS = PA.ID_PAIS
    GROUP BY PA.NOMBRE, PA.ID_PAIS
    ORDER BY PA.NOMBRE
)
SELECT PA.NOMBRE PAIS, CAT.CATEGORIA_PRODUCTO, CANTIDAD_UNIDADES
FROM CAT_TEMP CAT, PA_TEMP PA
WHERE CAT.CANTIDAD_UNIDADES = PA.CANTIDAD_UNIDAD
    AND PA.ID_PAIS = CAT.ID_PAIS
ORDER BY PA.NOMBRE


----------CONSULTA 8---------------
SELECT (EXTRACT(MONTH FROM ORD.FECHA_ORDEN)) MES , SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
FROM ORDEN ORD, PRODUCTO PR, VENDEDOR VEN, PAIS PA
WHERE VEN.ID_PAIS = PA.ID_PAIS
    AND ORD.ID_PRODUCTO = PR.ID_PRODUCTO
    AND ORD.ID_VENDOR = VEN.ID_VENDEDOR
    AND PA.NOMBRE = 'Inglaterra'
GROUP BY EXTRACT(MONTH FROM ORD.FECHA_ORDEN)
ORDER BY MES

-------- CONSULTA 9 --------------------
SELECT *
    FROM (
    SELECT (EXTRACT(MONTH FROM ORD.FECHA_ORDEN)) MES , SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
    FROM ORDEN ORD, PRODUCTO PR
    WHERE ORD.ID_PRODUCTO = PR.ID_PRODUCTO
    GROUP BY EXTRACT(MONTH FROM ORD.FECHA_ORDEN)
    ORDER BY MONTO DESC
) WHERE ROWNUM <=1
UNION
SELECT *
    FROM (
    SELECT (EXTRACT(MONTH FROM ORD.FECHA_ORDEN)) MES , SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
    FROM ORDEN ORD, PRODUCTO PR
    WHERE ORD.ID_PRODUCTO = PR.ID_PRODUCTO
    GROUP BY EXTRACT(MONTH FROM ORD.FECHA_ORDEN)
    ORDER BY MONTO ASC
) WHERE ROWNUM <=1

-------- CONSULTA 10 -------------------
SELECT PR.ID_PRODUCTO, PR.NOMBRE NOMBRE_PRODUCTO, SUM(ORD.CANTIDAD * PR.PRECIO) MONTO
FROM ORDEN ORD, PRODUCTO PR, CATEGORIA CAT
WHERE ORD.ID_PRODUCTO = PR.ID_PRODUCTO
    AND PR.ID_CATEGORIA = CAT.ID_CATEGORIA
    AND CAT.NOMBRE = 'Deportes'
GROUP BY PR.ID_PRODUCTO, PR.NOMBRE
ORDER BY ID_PRODUCTO ASC